"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { PrimeReactProvider, PrimeReactContext } from "primereact/api";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#F7F8FA]">
      <body className={inter.className}>
        <div className="mx-auto ">
          <PrimeReactProvider>
            <Navbar />
            <div className="">{children}</div>
          </PrimeReactProvider>
        </div>
      </body>
    </html>
  );
}
